version: '3.8'

services:
  insectos_app:
    build:
      context: .
      args:
        - SEARCH_API_URL=${SEARCH_API_URL:-https://api.insectlab.app}
    container_name: insectos_app
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Servicio opcional para desarrollo (descomentar si necesitas desarrollo en vivo)
  # insectos_app_dev:
  #   image: cirrusci/flutter:stable
  #   container_name: insectos_app_dev
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #     - /app/.dart_tool
  #     - /app/build
  #     - /app/.flutter-plugins-dependencies
  #   working_dir: /app
  #   command: flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0
  #   tty: true
  #   stdin_open: true
