name: insectos_app
description: "Una aplicación educativa sobre insectos agrícolas."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.1.0
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.2.2
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.15
  flutter_staggered_grid_view: ^0.7.0
  search_page: ^2.0.0
  image_picker: ^0.8.9
  permission_handler: ^10.4.0
  # Temporalmente deshabilitado para evitar problemas de compilación
  # geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/crops/
    - assets/images/insects/
    - assets/images/home/
    - assets/images/tech/
    - assets/icons/
